/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 earth.gltf 
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-f7a76c63ff1846afb2d606e5c8369c15
Title: Earth
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { MeshProps } from "@react-three/fiber";
import { motion } from "framer-motion-3d";
import { MotionValue } from "framer-motion";

interface ModelProps {
  meshRef: React.Ref<MeshProps>;
  x: MotionValue<number>;
  y: MotionValue<number>;
}

export const Earth = ({ meshRef, x, y, ...props }: ModelProps) => {
  const { nodes, materials } = useGLTF("/earth.gltf");

  return (
    <motion.mesh
      {...props}
      ref={meshRef}
      rotation-y={y}
      rotation-x={x}
      geometry={nodes.Object_4.geometry}
      material={materials["Scene_-_Root"]}
      scale={2}
    />
  );
};

useGLTF.preload("/earth.gltf");

export default Earth;
